const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const { map, filter, reject, reduce, find, findIndex, head, tail, last, init, take, drop, takeWhile, dropWhile, takeLast, dropLast, slice, splitAt, splitEvery, remove, insert, update, adjust, append, prepend, concat, flatten, chain, repeat, times, zip, zipObj, zipWith, groupBy, groupWith, sort, asc, desc, all, any, none, includes, without, difference, intersection, union, uniq, uniqBy, uniqWith, aperture, partition, span, pluck, project, fromPairs, toPairs, reverse, length, countBy, forEach, indexBy, interpose, intercalate, findLast, findLastIndex } = require('../dist/index.js');

describe('list', () => {
  it('map', () => { assert.deepEqual(map(x => x * 2, [1, 2, 3]), [2, 4, 6]); });
  it('filter', () => { assert.deepEqual(filter(x => x > 1, [1, 2, 3]), [2, 3]); });
  it('reject', () => { assert.deepEqual(reject(x => x > 1, [1, 2, 3]), [1]); });
  it('reduce', () => { assert.equal(reduce((a, b) => a + b, 0, [1, 2, 3]), 6); });
  it('find', () => { assert.equal(find(x => x > 1, [1, 2, 3]), 2); });
  it('findIndex', () => { assert.equal(findIndex(x => x > 1, [1, 2, 3]), 1); });
  it('findLast', () => { assert.equal(findLast(x => x < 3, [1, 2, 3, 2, 1]), 1); });
  it('findLastIndex', () => { assert.equal(findLastIndex(x => x < 3, [1, 2, 3, 2, 1]), 4); });
  it('head', () => { assert.equal(head([1, 2, 3]), 1); });
  it('tail', () => { assert.deepEqual(tail([1, 2, 3]), [2, 3]); });
  it('last', () => { assert.equal(last([1, 2, 3]), 3); });
  it('init', () => { assert.deepEqual(init([1, 2, 3]), [1, 2]); });
  it('take', () => { assert.deepEqual(take(2, [1, 2, 3]), [1, 2]); });
  it('drop', () => { assert.deepEqual(drop(2, [1, 2, 3]), [3]); });
  it('takeWhile', () => { assert.deepEqual(takeWhile(x => x < 3, [1, 2, 3, 4]), [1, 2]); });
  it('dropWhile', () => { assert.deepEqual(dropWhile(x => x < 3, [1, 2, 3, 4]), [3, 4]); });
  it('takeLast', () => { assert.deepEqual(takeLast(2, [1, 2, 3]), [2, 3]); });
  it('dropLast', () => { assert.deepEqual(dropLast(2, [1, 2, 3]), [1]); });
  it('slice', () => { assert.deepEqual(slice(1, 3, [1, 2, 3, 4]), [2, 3]); });
  it('splitAt', () => { assert.deepEqual(splitAt(2, [1, 2, 3, 4]), [[1, 2], [3, 4]]); });
  it('splitEvery', () => { assert.deepEqual(splitEvery(2, [1, 2, 3, 4, 5]), [[1, 2], [3, 4], [5]]); });
  it('remove', () => { assert.deepEqual(remove(1, 2, [1, 2, 3, 4]), [1, 4]); });
  it('insert', () => { assert.deepEqual(insert(1, 99, [1, 2, 3]), [1, 99, 2, 3]); });
  it('update', () => { assert.deepEqual(update(1, 99, [1, 2, 3]), [1, 99, 3]); });
  it('adjust', () => { assert.deepEqual(adjust(x => x * 10, 1, [1, 2, 3]), [1, 20, 3]); });
  it('append', () => { assert.deepEqual(append(4, [1, 2, 3]), [1, 2, 3, 4]); });
  it('prepend', () => { assert.deepEqual(prepend(0, [1, 2, 3]), [0, 1, 2, 3]); });
  it('concat', () => { assert.deepEqual(concat([1, 2], [3, 4]), [1, 2, 3, 4]); });
  it('flatten', () => { assert.deepEqual(flatten([1, [2, [3]], 4]), [1, 2, 3, 4]); });
  it('chain', () => { assert.deepEqual(chain(x => [x, x * 2], [1, 2, 3]), [1, 2, 2, 4, 3, 6]); });
  it('interpose', () => { assert.deepEqual(interpose(', ', [1, 2, 3]), [1, ', ', 2, ', ', 3]); });
  it('intercalate', () => { assert.deepEqual(intercalate([', '], [[1], [2], [3]]), [1, ', ', 2, ', ', 3]); });
  it('repeat', () => { assert.deepEqual(repeat(5, 3), [5, 5, 5]); });
  it('times', () => { assert.deepEqual(times(x => x * 2, 5), [0, 2, 4, 6, 8]); });
  it('zip', () => { assert.deepEqual(zip([1, 2, 3], ['a', 'b', 'c']), [[1, 'a'], [2, 'b'], [3, 'c']]); });
  it('zipObj', () => { assert.deepEqual(zipObj(['a', 'b'], [1, 2]), { a: 1, b: 2 }); });
  it('zipWith', () => { assert.deepEqual(zipWith((a, b) => a + b, [1, 2, 3], [10, 20, 30]), [11, 22, 33]); });
  it('groupBy', () => { assert.deepEqual(groupBy(x => x > 2 ? 'big' : 'small', [1, 2, 3, 4]), { small: [1, 2], big: [3, 4] }); });
  it('groupWith', () => { assert.deepEqual(groupWith((a, b) => a === b, [1, 1, 2, 2, 3]), [[1, 1], [2, 2], [3]]); });
  it('sort', () => { assert.deepEqual(sort((a, b) => a - b, [3, 1, 2]), [1, 2, 3]); });
  it('asc', () => { assert.deepEqual(asc([3, 1, 2]), [1, 2, 3]); });
  it('desc', () => { assert.deepEqual(desc([1, 2, 3]), [3, 2, 1]); });
  it('all', () => { assert.equal(all(x => x > 0, [1, 2, 3]), true); assert.equal(all(x => x > 1, [1, 2, 3]), false); });
  it('any', () => { assert.equal(any(x => x > 2, [1, 2, 3]), true); });
  it('none', () => { assert.equal(none(x => x > 10, [1, 2, 3]), true); });
  it('includes', () => { assert.equal(includes(2, [1, 2, 3]), true); });
  it('without', () => { assert.deepEqual(without([1, 2], [1, 2, 1, 3, 2, 4]), [3, 4]); });
  it('difference', () => { assert.deepEqual(difference([1, 2, 3], [2, 3, 4]), [4]); });
  it('intersection', () => { assert.deepEqual(intersection([1, 2, 3], [2, 3, 4]), [2, 3]); });
  it('union', () => { assert.deepEqual(union([1, 2, 3], [2, 3, 4]), [1, 2, 3, 4]); });
  it('uniq', () => { assert.deepEqual(uniq([1, 2, 1, 3, 2]), [1, 2, 3]); });
  it('uniqBy', () => { assert.deepEqual(uniqBy(x => x % 2, [1, 2, 3, 4, 5]), [1, 2]); });
  it('aperture', () => { assert.deepEqual(aperture(2, [1, 2, 3, 4]), [[1, 2], [2, 3], [3, 4]]); });
  it('partition', () => {
    const [evens, odds] = partition(x => x % 2 === 0, [1, 2, 3, 4, 5]);
    assert.deepEqual(evens, [2, 4]);
    assert.deepEqual(odds, [1, 3, 5]);
  });
  it('span', () => { assert.deepEqual(span(x => x < 3, [1, 2, 3, 4, 1]), [[1, 2], [3, 4, 1]]); });
  it('pluck', () => { assert.deepEqual(pluck('a', [{ a: 1 }, { a: 2 }]), [1, 2]); });
  it('project', () => { assert.deepEqual(project(['a', 'b'], [{ a: 1, b: 2, c: 3 }]), [{ a: 1, b: 2 }]); });
  it('fromPairs', () => { assert.deepEqual(fromPairs([['a', 1], ['b', 2]]), { a: 1, b: 2 }); });
  it('toPairs', () => { assert.deepEqual(toPairs({ a: 1, b: 2 }), [['a', 1], ['b', 2]]); });
  it('reverse', () => { assert.deepEqual(reverse([1, 2, 3]), [3, 2, 1]); });
  it('length', () => { assert.equal(length([1, 2, 3]), 3); });
  it('countBy', () => { assert.deepEqual(countBy(x => x > 2 ? 'big' : 'small', [1, 2, 3, 4]), { small: 2, big: 2 }); });
  it('forEach', () => {
    const xs = [];
    const result = forEach(x => xs.push(x), [1, 2, 3]);
    assert.deepEqual(xs, [1, 2, 3]);
    assert.deepEqual(result, [1, 2, 3]);
  });
  it('indexBy', () => {
    assert.deepEqual(indexBy(x => x.id, [{ id: 'a', v: 1 }, { id: 'b', v: 2 }]), { a: { id: 'a', v: 1 }, b: { id: 'b', v: 2 } });
  });
});
